from .bugplayer import BugPlayer
from .lelscan import LelScan
from .mangaorigin import MangaOriginToon
from .mangaowl import MangaOwl
from .scan1 import ScanOne
from .scantrad import ScanTrad
from .tbate import Tbate
from .toomics import Toomic
from .webtoons import WebToon
from .mangascan import MangaScan
