from .webtoons import WebToon
from .lelscan import LelScan
from .mangaorigin import MangaOriginToon
from .toomics import Toomic
from .scantrad import ScanTrad
from .tbate import Tbate
from .scan1 import ScanOne
from .bugplayer import BugPlayer
from .mangaowl import MangaOwl
