[tool.poetry]
name = "webtoons"
version = "0.1.0"
description = "Webtoons scrappers"
authors = ["Sebastien Nicolet <snicolet@student.42.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.22.0"
beautifulsoup4 = "^4.8.2"
ipython = "^7.12.0"
selenium = "^3.141.0"
click = "^7.0"
lxml = "^4.5.0"
aiofile = "^3.5.0"
aiohttp = "^3.7.4"
asyncio-pool = "^0.5.2"
mongomodel = "^0.5.2"
pydantic = "^1.8.2"
motor = "^2.5.1"
motorized = "^0.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
