[tool.poetry]
name = "webtoons"
version = "0.1.0"
description = "Webtoons scrappers"
authors = ["Sebastien Nicolet <snicolet@student.42.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
mongomodel = "0.5.2"
requests = "^2.22.0"
beautifulsoup4 = "^4.8.2"
ipython = "^7.12.0"
selenium = "^3.141.0"
click = "^7.0"
lxml = "^4.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
